language: generic

os: linux
env:
  - OCAML_VERSION=4.07.0

# Install OPAM from a newer PPA
addons:
  apt:
    sources:
      - sourceline: 'ppa:avsm/ocaml42+opam12'
    packages:
      - opam

# Install the specified version of OCaml
before_install:
- opam init --auto-setup --comp="$OCAML_VERSION"

# Install the required dependencies
install:
  - opam install --yes ocamlfind
  - opam install --yes ocamlbuild
  - opam install --yes oUnit
  - opam install --yes menhir

# Set the appropriate environment variables
before_script:
  - eval $(opam config env)

# Build and run the test suite
script:
  - make
  - make test